### ISSUE TITLE
expected time to ttd

### ISSUE THREAD

**Issue by Polandia94** [taxmeifyoucan/predict_ttd#1]
in webropsten.py, line 288 the program print the expected time. It's possible to add that information (or the info of line 290 time left to achieve) to https://bordel.wtf/ ?

**Comment by taxmeifyoucan** [comment]
It's the simplest linear prediction and it varies a lot based on current moment. On the bordel.wtf, it only activates one hour before TTD is expected to hit - this if statement is in wenmerge.py but I removed it for debugging on Ropsten.
I will set it up to print the output maybe 3 hours before the expected Ropsten merge with few minutes update period.
